### ISSUE TITLE
txpower control

### ISSUE THREAD

**Issue by eballarini** [openwisp/OpenWISP-Manager#15]
Hello to everyone,

It would be nice if OWM could set radio output power through a specific form in template and access point radio configuration page.

**Comment by morph027** [comment]
![screenshot from 2019-02-03 19-48-04](https://user-images.githubusercontent.com/600106/52180981-c73dec00-27ec-11e9-8aa8-c47e0f9a05e7.png)

I see this in my radio config ;)
