### ISSUE TITLE
Auto-channel support

### ISSUE THREAD

**Issue by dguerri** [openwisp/OpenWISP-Manager#5]
Mac80211 and midwifi drivers both support 'auto' channel selection.

This feature should be available through radio_template and radio openWISP views.

**Comment by morph027** [comment]
I see `auto` as valid option in my latest install:

![screenshot from 2019-02-03 19-48-04](https://user-images.githubusercontent.com/600106/52180987-e76dab00-27ec-11e9-910e-c5c14bf41f67.png)
